### ISSUE TITLE
Include LICENSE?

### ISSUE THREAD

**Issue by penyuan** [taylorconor/threeboard#7]
Beautiful project! Thank you for making the hardware designs, software, and documentation open source.

Can you please include LICENSE information for the hardware, software, and documentation in this repository, please? This way it will meet the [open source software](https://opensource.org/osd) and [open source hardware](https://www.oshwa.org/definition/) definitions. For the hardware designs, I suggest one of the [CERN Open Hardware Licenses 2.0](https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2). Maybe [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) for software, and [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) for documentation.

**Comment by taylorconor** [comment]
Thanks! Licenses added now in 475933d.

**Comment by penyuan** [comment]
Wow, thank you so much!
