### ISSUE TITLE
A couple components are now unavailable

### ISSUE THREAD

**Issue by 3bash** [taylorconor/threeboard#8]
Eager to try this project out as my first hardware project! Looks like these two parts are no longer in stock anywhere, any idea what could be a suitable replacement?

[ATMEGA34U4](https://www.digikey.com/en/products/detail/microchip-technology/ATMEGA32U4-AUR/2238241)

[FA-238 16.0000MB-C3](https://www.digikey.com/en/products/detail/epson/FA-238-16.0000MB-C3/2403459)

**Comment by taylorconor** [comment]
For the crystal the [403I35D16M00000](https://www.digikey.com/en/products/detail/epson/FA-238-16.0000MB-C3/2403459) looks like a drop-in replacement. The MCU should be in stock everywhere as it's really popular.

**Comment by 3bash** [comment]
Thanks for the crystal replacement! Although, looks like the MCU is ... too popular. I can't find it in stock anywhere :O

**Comment by taylorconor** [comment]
Oh wow you're right, I'm seeing 4-6 month lead times for it. I might have a few spare, email me!
